// =====================================================
// VEHICLE TRIP REPOSITORY
// CRUD operations for vehicle trips
// =====================================================

const BaseRepository = require('./BaseRepository');

class VehicleTripRepository extends BaseRepository {
    constructor() {
        super('vehicle_trip');
    }

    /**
     * Find trips by vehicle
     */
    findByVehicle(vehicleId) {
        return this.findAll({ vehicle_id: vehicleId });
    }

    /**
     * Find trips by date
     */
    findByDate(date) {
        return this.findAll({ trip_date: date });
    }

    /**
     * Find trips in date range
     */
    findByDateRange(startDate, endDate) {
        const sql = `
            SELECT vt.*, v.vehicle_number, v.vehicle_type, v.capacity_cubic_feet
            FROM ${this.tableName} vt
            JOIN vehicle v ON vt.vehicle_id = v.id
            WHERE vt.trip_date >= ? AND vt.trip_date <= ?
            ORDER BY vt.trip_date
        `;
        const { all } = require('../db');
        return all(sql, [startDate, endDate]);
    }

    /**
     * Find trip by vehicle and date
     */
    findByVehicleAndDate(vehicleId, date) {
        return this.findOne({ vehicle_id: vehicleId, trip_date: date });
    }

    /**
     * Get daily totals
     */
    getDailyTotals(date) {
        const sql = `
            SELECT 
                COUNT(DISTINCT vehicle_id) as vehicle_count,
                SUM(gravel_trips) as total_gravel_trips,
                SUM(clay_trips) as total_clay_trips,
                SUM(total_trips) as total_trips,
                SUM(total_qty_cubic_feet) as total_qty,
                SUM(trip_amount) as total_trip_amount,
                SUM(total_misc_expense) as total_misc_expense,
                SUM(total_amount) as total_amount
            FROM ${this.tableName}
            WHERE trip_date = ?
        `;
        const { get } = require('../db');
        return get(sql, [date]) || {
            vehicle_count: 0,
            total_gravel_trips: 0,
            total_clay_trips: 0,
            total_trips: 0,
            total_qty: 0,
            total_trip_amount: 0,
            total_misc_expense: 0,
            total_amount: 0
        };
    }

    /**
     * Get monthly summary
     */
    getMonthlySummary(year, month) {
        const monthStr = month.toString().padStart(2, '0');
        const startDate = `${year}-${monthStr}-01`;
        const endDate = `${year}-${monthStr}-31`;
        
        const sql = `
            SELECT 
                v.vehicle_number,
                v.vehicle_type,
                COUNT(*) as days_worked,
                SUM(vt.gravel_trips) as total_gravel_trips,
                SUM(vt.clay_trips) as total_clay_trips,
                SUM(vt.total_trips) as total_trips,
                SUM(vt.total_qty_cubic_feet) as total_qty,
                SUM(vt.trip_amount) as total_trip_amount,
                SUM(vt.total_misc_expense) as total_misc_expense,
                SUM(vt.total_amount) as total_amount
            FROM ${this.tableName} vt
            JOIN vehicle v ON vt.vehicle_id = v.id
            WHERE vt.trip_date >= ? AND vt.trip_date <= ?
            GROUP BY vt.vehicle_id
            ORDER BY v.vehicle_number
        `;
        const { all } = require('../db');
        return all(sql, [startDate, endDate]);
    }

    /**
     * Get grand total for date range
     */
    getGrandTotal(startDate, endDate) {
        const sql = `
            SELECT 
                SUM(gravel_trips) as total_gravel_trips,
                SUM(clay_trips) as total_clay_trips,
                SUM(total_trips) as total_trips,
                SUM(total_qty_cubic_feet) as total_qty,
                SUM(trip_amount) as total_trip_amount,
                SUM(total_misc_expense) as total_misc_expense,
                SUM(total_amount) as total_amount
            FROM ${this.tableName}
            WHERE trip_date >= ? AND trip_date <= ?
        `;
        const { get } = require('../db');
        return get(sql, [startDate, endDate]);
    }

    /**
     * Create a trip - override to handle defaults and calculate totals
     */
    create(data) {
        const tripData = {
            vehicle_id: data.vehicle_id,
            trip_date: data.trip_date,
            gravel_trips: data.gravel_trips || 0,
            clay_trips: data.clay_trips || 0,
            unit_cubic_feet: data.unit_cubic_feet || data.capacity_cubic_feet || 0,
            rate_per_cubic_feet: data.rate_per_cubic_feet || data.rate || 1.9,
            total_misc_expense: data.total_misc_expense || 0,
            remarks: data.remarks || null
        };

        // Calculate total_amount (trip_amount is auto-generated by DB)
        const totalTrips = tripData.gravel_trips + tripData.clay_trips;
        const tripAmount = totalTrips * tripData.unit_cubic_feet * tripData.rate_per_cubic_feet;
        tripData.total_amount = tripAmount + tripData.total_misc_expense;

        return this.insert(tripData);
    }
}

module.exports = new VehicleTripRepository();
